
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
cds:
  datasource:
    auto-config:
      enabled: true
#  multi-tenancy:
#    mtxs:
#      enabled: false
#    sidecar:
#      url: http://localhost:4005/
